version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  verify:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: aws version
      - run: |
          aws sts get-caller-identity | jq ".UserId"

workflows:
  the-fix:
    jobs:
      - verify
