version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1
  # new Orb version will only install AWS CLI v2 as a default
  # see https://circleci.com/developer/orbs/orb/circleci/aws-cli
  aws-cli-old: circleci/aws-cli@1.3.1

commands:
  check-aws-version:
    steps:
      - run: aws --version
  check-assumed-identity:
    steps:
      - run: |
          aws sts get-caller-identity | jq ".UserId"

jobs:
  verify:
    parameters:
      aws-cli-version:
        type: enum
        enum: ["2", "1"]
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    executor: aws-cli-old/default
    steps:
      - aws-cli-old/setup:
          version: << parameters.aws-cli-version >>
      - check-aws-version
      - check-assumed-identity

  control:
    # using latest orb, should install AWS CLI v2.x
    executor: aws-cli/default
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - aws-cli/setup
      - check-aws-version
      - check-assumed-identity
workflows:
  the-fix:
    jobs:
      - verify:
          matrix:
            parameters:
              aws-cli-version:
                - "1"
                - "2"
      - control
