version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1
  # new Orb version will only install AWS CLI v2 as a default
  # see https://circleci.com/developer/orbs/orb/circleci/aws-cli
  aws-cli-old: circleci/aws-cli@1.3.1

jobs:
  verify:
    parameters:
      aws-cli-version:
        type: string
        default: latest
      latest-orb:
        type: boolean
        default: true
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    executor: aws-cli/default
    steps:
      - when: << parameters.latest-orb >>
        steps:
          - aws-cli/setup:
              version: << parameters.aws-cli-version >>
      - unless: << parameters.latest-orb >>
        steps:
          - aws-cli-old/setup:
               version: << parameters.aws-cli-version >>   
      - run: aws --version
      - run: |
          aws sts get-caller-identity | jq ".UserId"

workflows:
  the-fix:
    jobs:
      - verify:
          name: verify-orb-v-1-3-1-aws-v2
          aws-cli-version: '2'
          latest-orb: false
      - verify:
          name: verify-orb-v-1-3-1-aws-v1
          aws-cli-version: '1'
          latest-orb: false
      - verify:
          name: verify-orb-v-3-1-1-aws-v2
          aws-cli-version: 'latest'
          latest-orb: true
